"""empty message

Revision ID: 33004d365e99
Revises: c46d3eab7f18
Create Date: 2020-03-02 16:59:41.693184

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '33004d365e99'
down_revision = 'c46d3eab7f18'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=80), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('categories')
    # ### end Alembic commands ###
